
setwd("~/R")
rm(list=ls())
data1<-read.csv("household_power_consumption.txt",sep=";",header = T,comment.char  = "",stringsAsFactors = FALSE)
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
data<- subset(data1, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data1)                             
hist(data$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()